### ISSUE TITLE
Systemd service hangs at shutdown

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri-installer-debian#90] opened 2020-04-09 14:32 UTC
Having an active Kolibri systemd unit makes systemd hang during shutdowns until timeout is reached.

Ref:
https://community.learningequality.org/t/stop-job-on-raspberry-pi-when-shutting-down/1482/10

Some more discussion here:
https://github.com/learningequality/kolibri/pull/6710

* Disabling the kolibri service makes it poweroff/reboot swiftly
* Running `systemctl stop kolibri` before `reboot` also works

![VirtualBox_Ubuntu 18 04 kolibri_09_04_2020_16_26_26](https://user-images.githubusercontent.com/374612/78906180-4ed15b80-7a7f-11ea-9a29-7d93ebb341fa.png)

There have been theories that Kolibri was stuck in its zeroconf service, but disabling this part did not work.

* Tested on Kolibri 0.13
* Should verify on 0.12 or 0.11 to see if a change in Kolibri caused this

**Comment by JamesKainer** [comment] 2020-04-11 00:01
I think I've found the problem. The issue is that /etc/init.d/kolibri creates a user session to start Kolibri and that gets abandoned. I'll explain in more detail. 

There were two stop jobs running at shutdown for sessions c1 and the interface alternates between them. I believe the first is Kolibri stopping as it takes about the right amount of time. The second job is unknown. That second job is the one that runs until the 90s default timeout and is then killed. I confirmed that this session is only running Kolibri with "sudo systemctl status". 

![systemctl status](https://user-images.githubusercontent.com/47008209/79029149-f5812f00-7b47-11ea-9edd-51c21ccd74bb.png)

To look at this further I ran "sudo systemctl list-units" and noticed that session c1 was in an abandoned state under "SUB". 

![sudo systemctl list-units2](https://user-images.githubusercontent.com/47008209/79029287-9374f980-7b48-11ea-9620-62ff8515a808.png)

I then ran "sudo systemctl status kolibri" and noticed that the Kolibri service said "active ( exited )".

![systemctl status kolibri 2](https://user-images.githubusercontent.com/47008209/79029509-873d6c00-7b49-11ea-8e75-21805fa1d2f7.png)

I researched this and abandoned and exited were there because kolibri was started in a user session that was abandoned and systemd didn't think it needed to manage it anymore. So, even though Kolibri is still running and working properly, that session is technically abandoned. A hint here is that the systemctl status kolibri log showed "pam_unix(su:session): session opened for user pi. 

The /etc/init.d/kolibri file runs Kolibri with su $KOLIBRI_USER -c "$KOLIBRI_COMMAND start" and that creates the logind session and then abandons it. For normal processes started that way that run quickly and exit you would set "KillUserProcesses=" to true and KillOnlyUsers= or KillExcludeUsers= in /etc/systemd/logind.conf to make sure the session exits and everything is killed after it's completed. In this case that would just stop Kolibri instantly as the init.d script isn't keeping it alive. 

To test this running as the pi user, I edited /etc/init.d/kolibri and replaced the user session stuff to start Kolibri directly

![edited init d kolibri](https://user-images.githubusercontent.com/47008209/79029882-3cbcef00-7b4b-11ea-9e86-15debe61268d.png)

Then ran "sudo systemctl daemon-reload' and "sudo systemctl restart kolibri". The status is now "active ( running )". 

![Kolibri active running](https://user-images.githubusercontent.com/47008209/79029990-c2d93580-7b4b-11ea-8614-9fd45d797cc8.png)

When I run "sudo shutdown now" the first Kolibri job is still there, takes 23 seconds to stop, and then the system shuts down. So, I believe that the second stop job that was hitting the 90s limit was related to the abandoned session itself. I'm not sure if the user session code is required or if this can be changed directly to just start kolibri as the pi user, but that does seem to be the issue. 

I believe the 23s stop job time for Kolibri is still related to the zeroconf .join() call and am looking at whether disabling it lowers that now.

**Comment by benjaoming** [comment] 2020-04-11 13:27
This is such fantastic work @JamesKainer  :heart_eyes:

I am able to reproduce the abandoned user session as well when I start Kolibri.

What behavior do you see when running `systemctl stop kolibri` manually before shutting down? Does it also make your system shut down just fine with no abandoned user session stalling it?

I suppose that this is some combination of the way we run `su` and the way Kolibri is daemonized. Something isn't done the right way.

I tried adding `PIDFile=/home/test/.kolibri/server.pid` for my test user, and I found that the PID even though it was correct, wasn't thought of as the correct one by systemd:

![image](https://user-images.githubusercontent.com/374612/79044889-55d7a580-7c08-11ea-9144-80324201fa0a.png)

There is a nifty shortcut to quickly edit an overlay of the systemd configuration: `sudo systemctl edit --full kolibri`. You will see an option `RemainAfterExit=Yes` - I don't think that's normally needed for a forking service, but it is probably also related to how systemd doesn't understand the forking that happens. Maybe it's because the sysvinit script forks with `su` before the `kolibri` process daemonizes...

**Comment by JamesKainer** [comment] 2020-04-11 20:40
Thanks @benjaoming :)

Without any changes on a default installation Kolibri stops anywhere between 6 and 20 seconds. On an installation with just zeroconf disabled and no initd change, kolibri always stops in about 6s. When Kolibri is stopped first the shutdown happens instantly. 

Changing RemainAfterExit to No makes Kolibri exit right away. My guess is that setting is what keeps it alive after the user session is abandoned.  

The 90s timeout is definitely because of the su and the remaining 23s delay when that's removed is definitely zeroconf as that goes away when it's disabled. 

I think you're onto something with the PID being wrong. I have been looking at the start-stop-daemon command to see if that could replace the way it's started now. It has PID and make pid switches that might be useful here.

**Comment by benjaoming** [comment] 2020-04-11 20:52
> Without any changes on a default installation Kolibri stops anywhere between 6 and 20 seconds. On an installation with just zeroconf disabled and no initd change, kolibri always stops in about 6s. 

Thanks for narrowing down the symptoms! The hanging shutdown certainly doesn't come from zeroconf then, but the slow shutdown should be fixed in Kolibri, so I'll file an issue.

> Changing RemainAfterExit to No makes Kolibri exit right away. My guess is that setting is what keeps it alive after the user session is abandoned.

I tried removing `RemainAfterExit` but it seemed to mean that Kolibri never starts -- or is killed immediately :)

> I have been looking at the start-stop-daemon command to see if that could replace the way it's started now.

It would be interesting: In #91, I wondered about abandoning Kolibri's own daemon features to use systemd's.. if we can use `start-stop-daemon` for `/etc/init.d/kolibri` as well, then there won't be any further reliance on the built-in daemon mechanism.

**Comment by JamesKainer** [comment] 2020-04-11 23:19
Thanks for all of the help looking at this @benjaoming. I think both fixes should bring this shutdown time to 6s which would be perfect.

Here's an example I found of start-stop-daemon being used in an init.d script that might be useful. https://gist.github.com/alobato/1968852 . I'll read over your notes from #91 and see if I can get a better idea of how that could be implemented. 

I should mention a bug I came across today while switching users in /etc/init.d/kolibri. I forgot to take a screenshot but this is the output.

● kolibri.service - LSB: kolibri daemon, an offline education platform
   Loaded: loaded (/etc/init.d/kolibri; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-04-11 18:39:51 BST; 2s ago
  Process: 1108 ExecStart=/etc/init.d/kolibri start (code=exited, status=1/FAILURE)

Apr 11 18:39:51 rachel kolibri[1108]:   File "/usr/lib/python3/dist-packages/kolibri/core/tasks/queue.py", line 1, in <module>
Apr 11 18:39:51 kolibri[1108]:     from kolibri.core.tasks.job import Job
Apr 11 18:39:51 kolibri[1108]:   File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 7, in <module>
Apr 11 18:39:51 kolibri[1108]:     from kolibri.core.tasks.utils import current_state_tracker
Apr 11 18:39:51 kolibri[1108]:   File "/usr/lib/python3/dist-packages/kolibri/core/tasks/utils.py", line 9, in <module>
Apr 11 18:39:51 kolibri[1108]:     from kolibri.deployment.default.cache import diskcache_cache
Apr 11 18:39:51 kolibri[1108]: ImportError: cannot import name 'diskcache_cache' from 'kolibri.deployment.default.cache' (/usr/lib/python3/dist-packages/kolibri/deployment/default/cache.
Apr 11 18:39:51 systemd[1]: kolibri.service: Control process exited, code=exited, status=1/FAILURE
Apr 11 18:39:51 systemd[1]: kolibri.service: Failed with result 'exit-code'.
Apr 11 18:39:51 systemd[1]: Failed to start LSB: kolibri daemon, an offline education platform.

It looks like it's related to [Fix cache db corruption #6511](https://github.com/learningequality/kolibri/pull/6511)

It's trying to import diskcache_cache from cache.py which happens [here](https://github.com/learningequality/kolibri/blob/c7bd7ac8e3cc494cb73247fd183652a25e054e74/kolibri/deployment/default/cache.py#L27) . If it fails in the try, then the except DatabaseError: calls recreate_cache(). I think when that errors diskcache_cache is only available in the scope of recreate_cache() and can't be imported by utils.py. Moving the content of recreate_cache() into the except fixed that. I also had to manually delete /home/pi/.kolibri/process_cache/cache.db one time.

**Comment by benjaoming** [comment] 2020-04-12 17:44
Thanks for the link to the `start-stop-daemon` example, that looks like where we wanna go. Kolibri has an environment that's created with `/etc/default/kolibri`, seems like the pattern in that script is doing the same. It also has a `-c / --chuid` option.

Please do let me know if you have good results patching things up with this, we should fast-track a quicker intermediate step towards more straight-forward systemd support.

**Comment by JamesKainer** [comment] 2020-04-13 05:21
Hi @benjaoming. I think I've found an alternative that would be great if you could review.

I switched the su -c to the [runuser](http://man7.org/linux/man-pages/man1/runuser.1.html) command and it seems to fix the issue. There is a short explanation of the difference between su and runuser in that manpage's description section. "it uses a different PAM configuration" is probably why this works. This is the code I've changed 

![sbin runuser](https://user-images.githubusercontent.com/47008209/79094167-79374900-7d0b-11ea-96d7-6d20263d6001.png)


after changing that I did "sudo systemctl daemon-reload" then "systemctl stop kolibri" and "sudo systemctl start kolibri". This is the output of "sudo systemctl status kolibri" now. 

![runuser running](https://user-images.githubusercontent.com/47008209/79093949-b3ecb180-7d0a-11ea-94ea-e37291537dd3.png)


Now it shows active ( running ). When I run "sudo systemctl status" to check for the session that used to get created, kolibri is now under system,slice and not that abandoned session. 

![system slice](https://user-images.githubusercontent.com/47008209/79093665-d0d4b500-7d09-11ea-8cd2-cc3ba6ff0e94.png)

The shutdown time is now about 6 seconds every time. This is running a fresh image of raspbian buster lite and your kolibri_0.13.2b1.dev0+git.24.g26bf9977-0ubuntu1_all.deb. I think this is about as simple as it gets for a fix. Would you consider this an appropriate fix or are there any downsides to it running under system.slice and not it's own session?

**Comment by benjaoming** [comment] 2020-04-13 09:45
That is super interesting, wondering what difference there is, but I guess systemd uses magic to track what happens in the sessions that it supervises.

In order to get the environment propagated to the `runuser` session, there are some sensitive settings, and I wonder if we get the environment from `/etc/default/kolibri` transferred as well as the correct `$HOME`.. did you try putting for instance `KOLIBRI_HOME=/tmp/test` in `/etc/kolibri/conf.d/test_home.conf` ?

> For backward compatibility, runuser defaults to not change the
> current directory and to only set the environment variables HOME and
> SHELL (plus USER and LOGNAME if the target user is not root).  This
> version of runuser uses PAM for session management.

> Note that runuser in all cases use PAM (pam_getenvlist()) to do final
> environment modification.  The command line options like --login or
> --preserve-environment affect environment before it's modified by
> PAM.

**Comment by JamesKainer** [comment] 2020-04-13 18:48
systemd does seem to rely on black magic haha. I think [this comment](https://danwalsh.livejournal.com/55588.html) might explain the runuser part of it. 

> su using the pam_stack was the cause of these errors.  Depending on which pam_modules you had in the /etc/pam.d/su configuration, certain access would be checked.  Services using su do not want/need these side effects of using the pam stack.  SELinux policy writers do not want to allow the access or add dontaudit rules all over the place.

> In order to fix this, we built a new application called runuser.  runuser is actually built from the su.c source code.  You just define the RUNUSER constant when compiling su.c.  Basically runuser is just the su command with the pam stack removed as well as verifying the command is running as root, not setuid.

> Whenever an service is running as root and wants to change UID using the shell it should use runuser.

I'd have to look at it more closely to see if that's what runuser does here on Raspbian, but that does sound about right. 

I'm going to spend some time with the configuration around this today to get an idea of what it does. I'll test --preserve-evironment and let you know what I find.

**Comment by JamesKainer** [comment] 2020-04-13 19:15
This is the content of the /tmp/test directory after setting KOLIBRI_HOME=/tmp/test in /etc/kolibri/conf.d/test_home.conf

![Kolibri test home](https://user-images.githubusercontent.com/47008209/79152095-762a7000-7d80-11ea-8460-cbc900c8a533.png)

**Comment by benjaoming** [comment] 2020-04-13 19:24
Awesome, and what you quoted says it's basically `su` without PAM, so the environment should be handled the same (confusing) way! :+1:

**Comment by benjaoming** [comment] 2020-04-13 19:34
@JamesKainer for giving proper credit to this change, would you mind opening up a PR replacing `su` with `runuser` ? I can get a beta release versioned and built on Launchpad for further testing.

**Comment by JamesKainer** [comment] 2020-04-13 21:39
Thanks @benjaoming. I have made a pull request. I hope I've done that correctly. Let me know if there's anything more I can do to help with this.

**Comment by jredrejo** [comment] 2020-04-24 15:33
Closing after the related PRs are merged

**Closed by jredrejo** 2020-04-24 15:33 UTC
